### PR TITLE
BlockSpy

### PR DESCRIPTION
**Pull request by craze3**
[https://blockspy.net](https://blockspy.net) is now live and working! Thank you to ConsenSys and Alethio!

### CODE REVIEW

**Comment by zherring** [comment]
@craze3 I'm getting a merge conflict with your .DS_Store and DeFi/submissions.md. Please resolve in 24 hours.

**Comment by edsonayllon** [comment]
Wow, this project's great! 

`.DS_Store` is an OS generated file on MacOS. Typically, it's supposed to be ignored inside of `.gitignore`. If it has been uploaded, you might need to manually remove it, even after adding it to the `.gitignore`. Most likely, you just need to find that file in your repo and delete it. 

Here are a few resources:
- https://help.github.com/en/articles/deleting-files
- https://stackoverflow.com/questions/14237674/how-to-delete-files-in-github-using-the-web-interface
- https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo

Use whichever one makes the most sense to you.

Also, it looks like your project changed the `submission.md` file for everyone, instead of adding a copy inside the project folder. To fix that, move the `submission.md` file to inside of your project folder, along with `README.md` (so it's in your project and not a readme for everyone's projects). And copy and paste the original `submission.md` file into the DeFi folder.

**Comment by craze3** [comment]
Thanks @edsonayllon , should i do it here or can i open a new PR ?

**Comment by craze3** [comment]
i remove .DS_Store ... can you try again ?

**Comment by zherring** [comment]
@craze3 IT still says I have a merge conflict. Could you please open another PR?

**Comment by zherring** [comment]
Fixed it on my end. Appreciate the patience and thanks for the work @craze3 !

**Pull request merged**
